spring:
  application:
    name: prometheus-demo

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    prometheus:
      enabled: true

  prometheus:
    metrics:
      export:
        enabled: true
